name: Deploy Azure Functions

on:
  push:
    branches: [ main ]
    paths:
      - 'functions/**'
      - '.github/workflows/deploy-functions.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - test
          - prod

env:
  AZURE_FUNCTIONAPP_NAME: 'blog-automation-func'  # set this to your function app name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './functions'   # set this to the path to your function app project
  PYTHON_VERSION: '3.11'                          # set this to the python version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'workflow_dispatch' && inputs.environment || 'dev' }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Create and configure virtual environment
      run: |
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/requirements-functions.txt

    - name: Run tests
      run: |
        cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        source ../.venv/bin/activate
        # Run any tests here if you have them
        # pytest tests/

    - name: Build and package functions
      run: |
        cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        mkdir -p dist
        zip -r dist/function-app.zip . -x "*.git*" -x "dist/*" -x "*.venv*" -x "*.vscode*" -x "*.pytest_cache*" -x "*__pycache__*" -x "*.env"

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Determine resource group based on environment
      id: set-rg
      run: |
        if [ "${{ github.event_name == 'workflow_dispatch' && inputs.environment || 'dev' }}" == "prod" ]; then
          echo "RESOURCE_GROUP=blog-automation-prod-rg" >> $GITHUB_ENV
        elif [ "${{ github.event_name == 'workflow_dispatch' && inputs.environment || 'dev' }}" == "test" ]; then
          echo "RESOURCE_GROUP=blog-automation-test-rg" >> $GITHUB_ENV
        else
          echo "RESOURCE_GROUP=blog-automation-dev-rg" >> $GITHUB_ENV
        fi

    - name: Deploy to Azure Function App
      uses: azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/dist/function-app.zip
        respect-funcignore: true
        scm-do-build-during-deployment: true
        enable-oryx-build: true

    - name: Logout from Azure
      run: |
        az logout
      if: always()