name: Deploy Azure Reference (DO NOT RUN)

# This is a reference file showing proper parameters for deployment
# DO NOT trigger this workflow - it's for documentation only

on:
  workflow_dispatch:  # Manual trigger only

env:
  AZURE_FUNCTIONAPP_NAME: "blogauto-dev-function"
  PYTHON_VERSION: '3.11'  # Use consistent Python version
  RESOURCE_GROUP: "blogauto-dev-rg"
  LOCATION: 'eastus'
  ENVIRONMENT: 'dev'
  PROJECT_NAME: "blogauto"  # This must NOT be empty

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Create resource group if not exists
      run: |
        az group create --name ${{ env.RESOURCE_GROUP }} --location ${{ env.LOCATION }}
        
    - name: Deploy Bicep
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.RESOURCE_GROUP }}  # THIS MUST BE SET
        template: ./infra/main.bicep
        parameters: projectName=${{ env.PROJECT_NAME }} environment=${{ env.ENVIRONMENT }} location=${{ env.LOCATION }}
        deploymentName: 'github-${{ github.run_number }}'
        failOnStdErr: false