name: Deploy Blog Automation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: ${{ format('blogauto-{0}-function', secrets.ENVIRONMENT || 'dev') }}
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'src'
  PYTHON_VERSION: '3.9'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v1
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Resolve Project Dependencies Using Pip'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd

    - name: 'Debug Environment Variables'
      run: |
        echo "Function App Name: ${{ env.AZURE_FUNCTIONAPP_NAME }}"
        echo "Package Path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
        echo "Python Version: ${{ env.PYTHON_VERSION }}"
        echo "Environment: ${{ secrets.ENVIRONMENT != '' && secrets.ENVIRONMENT || 'dev' }}"

    - name: 'Deploy Bicep Infrastructure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy Bicep Templates'
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
        template: ./infra/main.bicep
        parameters: projectName="${{ secrets.PROJECT_NAME }}" environment="${{ secrets.ENVIRONMENT != '' && secrets.ENVIRONMENT || 'dev' }}"

    # Wait for the Function App to be created
    - name: 'Wait for Function App to be ready'
      run: |
        echo "Waiting 30 seconds for the Function App resource to be fully provisioned..."
        sleep 30
        
    - name: 'Deploy Azure Function'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        scm-do-build-during-deployment: true
        enable-oryx-build: true
      env:
        AZURE_FUNCTIONAPP_NAME: ${{ env.AZURE_FUNCTIONAPP_NAME }}
