name: Deploy with Script

on:
  workflow_dispatch:  # This allows manual triggering
    inputs:
      resource_group:
        description: 'Azure Resource Group Name'
        required: true
        default: 'blogauto-dev-rg'
      project_name:
        description: 'Project Name'
        required: true
        default: 'blogauto'
      environment:
        description: 'Environment (dev, test, prod)'
        required: true
        default: 'dev'
      location:
        description: 'Azure Region'
        required: true
        default: 'eastus'

env:
  AZURE_FUNCTIONAPP_NAME: "${{ github.event.inputs.project_name }}-${{ github.event.inputs.environment }}-function"
  PYTHON_VERSION: '3.11'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install azure-cli
        
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Debug Input Variables
      run: |
        echo "Resource Group: ${{ github.event.inputs.resource_group }}"
        echo "Project Name: ${{ github.event.inputs.project_name }}"
        echo "Environment: ${{ github.event.inputs.environment }}"
        echo "Location: ${{ github.event.inputs.location }}"
        
    - name: Run deployment script
      run: |
        python deploy-direct.py \
          --resource-group "${{ github.event.inputs.resource_group }}" \
          --project-name "${{ github.event.inputs.project_name }}" \
          --environment "${{ github.event.inputs.environment }}" \
          --location "${{ github.event.inputs.location }}"